title: Tanumoy Dhar
logo: /assets/img/profile.png
#description: text below image
# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: brown

social_links:
  - { platform: google_scholar, user_url: "https://scholar.google.fr/citations?user=II08p2UAAAAJ&hl=en&oi=ao" }

show_downloads: false
theme: jekyll-theme-minimal
