title: Tanumoy Dhar
logo: /assets/img/profile.png
#description: text below image
# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

google_analytics:
show_downloads: false
theme: jekyll-theme-minimal
